Web/Models/Director.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Director
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Director()
        {
            this.Director_Movie = new HashSet<Director_Movie>();
            this.Director_TVSeries = new HashSet<Director_TVSeries>();
        }
    
        public string DirectorID { get; set; }
        public string FullName { get; set; }
        public string Images { get; set; }
        public string BirthName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public string Height { get; set; }
        public string Nationality { get; set; }
        public string Picture { get; set; }
        public string Born { get; set; }
        public string About { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Director_Movie> Director_Movie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Director_TVSeries> Director_TVSeries { get; set; }
    }
}

Web/Controllers/DirectorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class DirectorController : Controller
    {
        Movie12Entities db = new Movie12Entities();
        // GET: Director
        public ActionResult Profile(string DirectorID="D1")
        {
            Director director = db.Directors.SingleOrDefault(n => n.DirectorID == DirectorID);
            if (director == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            var directors = db.Director_Movie.Where(n => n.DriectorID == DirectorID).ToList();
            ViewData["moviejoined"] = directors;
            return View(director);
        }
        public PartialViewResult Moviesjoined(string DirectorID = "D1")
        {
            var DirectorMovie = db.Director_Movie.Where(n => n.DriectorID == DirectorID).ToList();
            var DirectorTVSeries = db.Director_TVSeries.Where(n => n.DirectorID == DirectorID).ToList();
            ViewData["moviejoined"] = DirectorMovie;
            ViewData["moviejoined2"] = DirectorTVSeries;
            return PartialView();
        }
    }
}

Web/Views/Director/Moviesjoined.cshtml
@using Web.Models;
<div class="section">
    <div class="container">
        <div class="movies-slide carousel-nav-center owl-carousel owl-loaded owl-drag">
            <div class="owl-stage-outer">
                <div class="owl-stage" style="transform: translate3d(-310px, 0px, 0px); transition: all 0s ease 0s; width: 2170px;">
                    @foreach (var item in ViewData["moviejoined"] as List<Director_Movie>)
                    {
                        <div class="owl-item" style="width: 295px; margin-right: 15px;">
                            <a href="@Url.Action("DetailMovie","Detail",new { @MovieID = item.Movie.MovieID})" class="movie-item">
                                <img src="@Url.Content("~/Images/Index/"+item.Movie.Image)" alt="">
                                <div class="movie-item-content">
                                    <div class="movie-item-title">
                                        @item.Movie.Name
                                    </div>
                                    <div class="movie-infos">
                                        <div class="movie-info">
                                            <i class="bx bxs-star"></i>
                                            <span>9.5</span>
                                        </div>
                                        <div class="movie-info">
                                            <i class="bx bxs-time"></i>
                                            <span>120 mins</span>
                                        </div>
                                        <div class="movie-info">
                                            <span>HD</span>
                                        </div>
                                        <div class="movie-info">
                                            <span>16+</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                    @foreach (var item in ViewData["moviejoined2"] as List<Director_TVSeries>)
                    {
                        <div class="owl-item" style="width: 295px; margin-right: 15px;">
                            <a href="@Url.Action("DetailTVSeries","TVSeries",new { @MovieID = item.PhimBo.ID})" class="movie-item">
                                <img src="@Url.Content("~/Images/Index/"+item.PhimBo.Images)" alt="">
                                <div class="movie-item-content">
                                    <div class="movie-item-title">
                                        @item.PhimBo.Name
                                    </div>
                                    <div class="movie-infos">
                                        <div class="movie-info">
                                            <i class="bx bxs-star"></i>
                                            <span>9.5</span>
                                        </div>
                                        <div class="movie-info">
                                            <i class="bx bxs-time"></i>
                                            <span>120 mins</span>
                                        </div>
                                        <div class="movie-info">
                                            <span>HD</span>
                                        </div>
                                        <div class="movie-info">
                                            <span>16+</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </div><div class="owl-nav"><button type="button" role="presentation" class="owl-prev"><i class="bx bx-chevron-left"></i></button><button type="button" role="presentation" class="owl-next"><i class="bx bx-chevron-right"></i></button></div><div class="owl-dots disabled"></div>
        </div>
    </div>
</div>

Web/Views/Director/Profile.cshtml
@model Web.Models.Director
@using Web.Models;
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/css/Detail/css.css" rel="stylesheet" />
<link href="~/css/Detail/classy-nav.css" rel="stylesheet" />
<link href="~/css/Detail/font-awesome.min.css" rel="stylesheet" />
<style>
    .btn {
        cursor: pointer;
    }
</style>
<div class="container clear_navar" style="padding-top: 60px;">

    <div class="row" style="max-width: 80%">

        <div class="col-xl-8" style="height: auto; padding-top: 40px">
            <div class=" detail">
                <div style="   background-image :src(" /Images/Index/wanda-banner.sjpg")">
                    <div class="row" style="margin: 10px; box-shadow: 0 4px 8px 0 rgb(0 0 0 / 20%), 0 6px 20px 0 rgb(0 0 0 / 40%); ">

                        <div style="width :50%" class="col-12 col-sm-4 col-md-4 ">
                            <div class="section-header">
                                @Html.DisplayFor(model => model.FullName)

                            </div>
                            @*<img width="40%" src="@Url.Content("~/Images/Index/"+@Html.DisplayFor(model => model.Image))">*@
                            <img width="40%" src="~/Images/Directors/Profile/@Html.DisplayFor(model => model.Picture)" />
                        </div>
                        <div style="width: 50%; padding-top: 70px;" class="col-12 col-sm-8 col-md-8">
                            <div class="chitiet" style="padding-top: 20px;width:100%;margin:auto">
                                <table>
                                    <tbody>
                                        <tr>
                                            <td width="100px" style="color: white; font-weight: bold;">Birth Name</td>
                                            <td>   @Html.DisplayFor(model => model.BirthName)</td>
                                        </tr>
                                        <tr>
                                            <td width="100px" style="color: white; font-weight: bold;">Date of Birth</td>
                                            <td>   @Html.DisplayFor(model => model.DateofBirth)</td>
                                        </tr>
                                        <tr>
                                            <td width="100px" style="color: white; font-weight: bold;">Born</td>
                                            <td>   @Html.DisplayFor(model => model.Born)</td>
                                        </tr>
                                        <tr>
                                            <td style="color:white; font-weight: bold;">Height</td>
                                            <td>   @Html.DisplayFor(model => model.Height)</td>
                                        </tr>
                                        <tr>
                                            <td style="color: white; font-weight: bold;">Nationality</td>
                                            <td>   @Html.DisplayFor(model => model.Nationality)</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="film-desc" style="padding-top: 15px; margin: 20px">
                    <div class="section-header">
                        Detail
                    </div>
                    <div id="summary">
                        <p class="collapse" id="collapseSummary">
                            <td>   @Html.DisplayFor(model => model.About)</td>
                        </p>
                        <p class="collapse" id="collapseSummary" style="padding">
                            <td>   @Html.DisplayFor(model => model.About)</td>
                        </p>
                        <a class="collapsed" data-toggle="collapse" href="#collapseSummary" aria-expanded="false" aria-controls="collapseSummary"></a>
                    </div>
                </div>
            </div>
            <div class="section-header">
                movies have Joined
            </div>

        </div>
    </div>
    @Html.Action("Moviesjoined", "Director")
</div>